name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Ruff (lint)
        run: ruff check .
      - name: Mypy (type-check)
        run: mypy app
      - name: Pytest
        run: pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: api
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f apps/api/docker/Dockerfile -t bar-api:ci apps/api
